// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using devices.Persistance;

namespace devices.Persistance.Migrations
{
    [DbContext(typeof(DatabaseService))]
    partial class DatabaseServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("devices.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DeviceStatus")
                        .HasColumnType("integer");

                    b.Property<int>("DeviceType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid[]>("RelatedDevices")
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93db428b-aad2-4a0c-bdb7-8d7941c23649"),
                            DeviceStatus = 2,
                            DeviceType = 0,
                            Name = "Device 1",
                            RelatedDevices = new[] { new Guid("81c066fb-3b81-40e8-a863-3ccf589b6119"), new Guid("81c066fb-3b81-40e8-a863-3ccf589b6119"), new Guid("bfaeb67a-6d2a-4e9c-b615-07f4052e0966") }
                        },
                        new
                        {
                            Id = new Guid("81c066fb-3b81-40e8-a863-3ccf589b6119"),
                            DeviceStatus = 0,
                            DeviceType = 1,
                            Name = "Device 2"
                        },
                        new
                        {
                            Id = new Guid("bfeefcc2-d1a7-4e48-b221-8ace75a69d8b"),
                            DeviceStatus = 2,
                            DeviceType = 2,
                            Name = "Device 3"
                        },
                        new
                        {
                            Id = new Guid("bfaeb67a-6d2a-4e9c-b615-07f4052e0966"),
                            DeviceStatus = 2,
                            DeviceType = 3,
                            Name = "Device 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
